spring.application.name=FilmRentalStore
server.port=${SERVER_PORT:0}


# Database Configuration
spring.datasource.url=jdbc:mysql://singh31.tailc064ec.ts.net:3306/sakila
spring.datasource.username=teamuser

spring.datasource.password=${DB_PASSWORD:password123}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# No MVC templates are present in this project.
spring.thymeleaf.check-template-location=false
