spring.application.name=FilmRentalStore

# Enforces port 8081
server.port=8089

# Database Configuration (Ensure your Tailscale VPN is active to connect to this remote DB)

spring.datasource.url=jdbc:mysql://localhost:3306/sakila
#spring.datasource.url=jdbc:mysql://singh31.tailc064ec.ts.net:3306/sakila
#spring.datasource.username=teamuser
#spring.datasource.password=password123
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA/Hibernate Properties
spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=true
spring.jpa.open-in-view=false

# Thymeleaf Configuration
# Requires src/main/resources/templates/ to exist
spring.thymeleaf.check-template-location=false
